steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'grc.io/$_PROJECT_ID/$_DATA_INGESTION:$COMMIT_SHA', '.']
    dir: $_COMPONENTS_FOLDER/$_DATA_INGESTION
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'grc.io/$_PROJECT_ID/$_DATA_PREPARATION:$COMMIT_SHA', '.']
    dir: $_COMPONENTS_FOLDER/$_DATA_PREPARATION
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'grc.io/$_PROJECT_ID/$_MODEL_TRAINING:$COMMIT_SHA', '.']
    dir: $_COMPONENTS_FOLDER/$_MODEL_TRAINING
  - name: 'gcr.io/$_PROJECT_ID/kfp-cli'
    env:
      - 'DOCKER_CONTAINER_REGISTRY_BASE_URL=$_DOCKER_CONTAINER_REGISTRY_BASE_URL'
      - 'TAG=$COMMIT_SHA'
    args:
      - '-c'
      - 'dsl-compile --py pipeline.py --output pipeline.tar.gz'
    dir: $_PIPELINE_FOLDER

images:
  - '$_DOCKER_CONTAINER_REGISTRY_BASE_URL/forecasting_example-data-ingestion:$COMMIT_SHA'
  - '$_DOCKER_CONTAINER_REGISTRY_BASE_URL/forecasting_example-data-preparation:$COMMIT_SHA'
  - '$_DOCKER_CONTAINER_REGISTRY_BASE_URL/forecasting_example-model-training:$COMMIT_SHA'
  - '$_DOCKER_CONTAINER_REGISTRY_BASE_URL/forecasting_example-model-evaluation:$COMMIT_SHA'